name: Windows Build
on: [push,create]
jobs:
  pkt-electrum-windows-builder:
    # if: "contains(github.event.commits[0].message, 'REBUILD_DOCKER')" need?
    runs-on: ubuntu-latest
    environment: docker_creds
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.2.2
        with:
          context: contrib/build-wine
          push: true
          cache-from: type=registry,ref=cjd1/pkt-electrum-windows-builder:latest
          cache-to: type=inline
          tags: |
            cjd1/pkt-electrum-windows-builder:latest

  windows:
    runs-on: ubuntu-latest
    environment: docker_creds
    needs: pkt-electrum-windows-builder
    services:
      electrum-wallet:
        image: cjd1/pkt-electrum-windows-builder:latest
        credentials:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "VERSION=$(git describe --tags --dirty --always)" >> $GITHUB_ENV

      - name: Make App Image
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          image: cjd1/pkt-electrum-windows-builder:latest
          shell: bash
          options: >
            -v ${{ github.workspace }}:/opt/wine64/drive_c/electrum
          run: >
            cd /opt/wine64/drive_c/electrum/contrib/build-wine && /opt/wine64/drive_c/electrum/contrib/build-wine/make_win.sh

      - uses: actions/upload-artifact@main
        with:
          path: contrib/build-wine/dist/electrum-${{ env.VERSION }}-setup.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: contrib/build-wine/dist/electrum-${{ env.VERSION }}-setup.exe

